name: Build the last successful automatic rebase of aem-next branch

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - 'Rebase on top of QubesOS main and build RPMs'
    types:
      - completed

jobs:
  qubes-dom0-package:
    uses: TrenchBoot/.github/.github/workflows/qubes-dom0-packagev2.yml@add-rebase-script
    with:
      qubes-component: 'vmm-xen'
      qubes-component-branch: 'aem-next-test-rebased'
      qubes-pkg-src-dir: '.'
      qubes-pkg-version: '4.19.4'
  trigger-woodpecker-cicd:
    needs: qubes-dom0-package
    uses: TrenchBoot/.github/.github/workflows/trigger-woodpecker-pipeline.yml@add-rebase-script
    secrets:
      woodpecker-token: ${{ secrets.WOODPECKER_TOKEN }}
    with:
      api-url:  'https://ci.3mdeb.com'
      owner:    'zarhus'
      repo:     'trenchboot-release-cicd-pipeline'
      ref:      'sign-and-publish-rc-rpms'
      inputs: >-
        --input GITHUB_REPO=xen
        --input GITHUB_SHA=${{ github.sha }}
        --input GITHUB_RUN_ID=${{ github.run_id }}
        --input QUBES_COMPONENT=vmm-xen
