name: Build the last successful automatic rebase of aem-next branch

on:
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read-version.outputs.version }}
    steps:
      - uses: actions/checkout@v6
      - name: Read version of the QubesOS Component from version file
        id: read-version
        run: echo "version=$(cat version)" >> $GITHUB_OUTPUT
  qubes-dom0-package:
    needs: get-version
    uses: TrenchBoot/.github/.github/workflows/qubes-dom0-packagev2.yml@add-rebase-script
    with:
      qubes-component: 'vmm-xen'
      qubes-component-branch: 'aem-next-rebased'
      qubes-pkg-src-dir: '.'
      qubes-pkg-version: ${{ needs.get-version.outputs.version }}
  trigger-woodpecker-cicd:
    needs: qubes-dom0-package
    uses: TrenchBoot/.github/.github/workflows/trigger-woodpecker-pipeline.yml@add-rebase-script
    secrets:
      woodpecker-token: ${{ secrets.WOODPECKER_TOKEN }}
    with:
      api-url:  'https://ci.3mdeb.com'
      owner:    'zarhus'
      repo:     'trenchboot-release-cicd-pipeline'
      ref:      'sign-and-publish-rc-rpms'
      inputs: >-
        --input GITHUB_REPO=xen
        --input GITHUB_SHA=${{ github.sha }}
        --input GITHUB_RUN_ID=${{ github.run_id }}
        --input QUBES_COMPONENT=vmm-xen
        --input WORKFLOW=sign-and-publish-test-rpms
